# Generated by Django 5.1.7 on 2025-03-23 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avg_budget',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='travel_days',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='travel_destination',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
