# Generated by Django 5.1.7 on 2025-03-24 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_user_avg_budget_user_travel_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='food_preference',
            field=models.CharField(choices=[('VEG', 'Vegetarian'), ('NON_VEG', 'Non-Vegetarian'), ('VEGAN', 'Vegan'), ('ANY', 'Any')], default='ANY', max_length=10),
        ),
        migrations.CreateModel(
            name='TravelInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggested_accommodation', models.CharField(max_length=255)),
                ('suggested_transportation', models.CharField(max_length=255)),
                ('suggested_activities', models.TextField()),
                ('recommended_budget', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.user')),
            ],
        ),
    ]
