# Generated by Django 5.1.7 on 2025-03-24 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_user_food_preference_travelinformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=200)),
                ('interests', models.TextField()),
                ('itinerary', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
