# Generated by Django 5.1.7 on 2025-03-24 14:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_travelrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelrequest',
            name='travel_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='travel_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='travel_requests', to='API.user'),
            preserve_default=False,
        ),
    ]
