# Generated by Django 5.1.7 on 2025-03-24 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_travelrequest_travel_date_travelrequest_travel_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelrequest',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
