# Generated by Django 5.1.7 on 2025-03-29 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_alter_travelrequest_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='travel_days',
            new_name='travel_duration',
        ),
        migrations.RemoveField(
            model_name='travelrequest',
            name='travel_time',
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='avg_budget',
            field=models.IntegerField(default=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='food_prefference',
            field=models.CharField(choices=[('VEG', 'Vegetarian'), ('NON_VEG', 'Non-Vegetarian'), ('VEGAN', 'Vegan'), ('ANY', 'Any')], default='ANY', max_length=10),
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='travel_duration',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='weather',
            field=models.TextField(blank=True, null=True),
        ),
    ]
