# Generated by Django 5.1.7 on 2025-03-29 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_rename_travel_days_user_travel_duration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itinerary', models.TextField()),
                ('itinerary_id', models.IntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.travelrequest')),
            ],
        ),
    ]
